version: '3'  
services:
  fastapi:
    build: ./api
    ports:
      # all replicas listen at port 8000 - the host port isn't defined, i think is automatically defined then detected by nginx
      - "8000"
    volumes:
      # bind mount
      - type: bind
        source: ./api/models
        target: /api/models
        read_only: true
      - type: bind
        # absolute path to the ssl folder in the host machine
        source: /etc/letsencrypt/live/dsaichingfhen.com 
        # absolute path inside the container   
        target: /ssl
        read_only: true 
      - type: bind
        # absolute path to the ssl folder in the host machine
        source: /etc/letsencrypt/archive/dsaichingfhen.com 
        # absolute path inside the container   
        target: /ssl2
        read_only: true 
    deploy:
      replicas: 3
    
  nginx:
    build: ./nginx
    ports:
      # nginx listens at port 80 and 443 for http and https messages
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
    volumes:
      - type: bind
        source: ./nginx/nginx.conf    # relative to compose file
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        # absolute path to the ssl folder in the host machine
        source: /etc/letsencrypt/live/dsaichingfhen.com 
        # absolute path inside the container   
        target: /ssl
        read_only: true 
